#Numpy

**np.array VS Python List**

In [ ]:
import numpy as np

A= [1,2,3,4,5]
B= [0.5, 0.5, 0.5, 0.5, 0.5]

print ('A =', A)                     
print ('B =', B) 

#____________________________________________________________________________________________________________________
print ('\n')

print ('A+B =', A+B)                     #note that A and B are "List" and they get "Concatinated"
print ('A*2 =', A*2)                     #note that A is a "List" and if you multiply it by 2, it gets "Concatinated"
#print ('A*B =', A*B)                    #This will not work!
# A.shape                                #This will not work! use len(A)


#____________________________________________________________________________________________________________________
print ('\n') 
A_np= np.array(A)                #Turn the "List" into Numpy-Array
B_np= np.array(B)

print ('A_np + B_np =', A_np + B_np) 
print ('A_np * B_np =', A_np * B_np)

print ('\n') 
print ('Shape  of A_np  =', A_np.shape)
print ('Length of A_np  =', len(A_np))

A = [1, 2, 3, 4, 5]
B = [0.5, 0.5, 0.5, 0.5, 0.5]


A+B = [1, 2, 3, 4, 5, 0.5, 0.5, 0.5, 0.5, 0.5]
A*2 = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


A_np + B_np = [1.5 2.5 3.5 4.5 5.5]
A_np * B_np = [0.5 1.  1.5 2.  2.5]


Shape  of A_np  = (5,)
Length of A_np  = 5


In [ ]:
A = [0.1, 0.9, 0.4, 0.2, 0.8, 0.1, 0.6] 
A= np.array(A)
print ('A:',A)
print ('A[0]:',A[0])
print ('A[1]:',A[1])
print ('A<0.5:',A<0.5)
A[A<0.5]


A: [0.1 0.9 0.4 0.2 0.8 0.1 0.6]
A[0]: 0.1
A[1]: 0.9
A<0.5: [ True False  True  True False  True False]


array([0.1, 0.4, 0.2, 0.1])

In [ ]:
A = [0.1, 0.9, 0.4, 0.2, 0.8, 0.1, 0.6]
A= np.array(A) 
print ([A<=0.5])                          #This is a True/False array
np.array([A<=0.5]).astype(int)


[array([ True, False,  True,  True, False,  True, False])]


array([[1, 0, 1, 1, 0, 1, 0]])

In [ ]:
A = [0.1, 0.9, 0.4, 0.2, 0.8, 0.1, 0.6] 
A= np.array(A)
A[A<0.5]= 0
A[A>0.5]= 1
A


array([0., 1., 0., 0., 1., 0., 1.])

**Reshapeing a matrix**

In [ ]:
A = [  [1,2,3], [4,5,6]    ]        # Remember that this is a list. 
#A.shape                            #So, A.shape wouldn't work
len(A)    

2

In [ ]:
type(A)                             #Verify that A is a list!

list

In [ ]:
np.reshape(A,6)                      #a list CAN be reshaped!

array([1, 2, 3, 4, 5, 6])

In [ ]:
B = [  [1,2,3], [4,5,6], [7,8,9], [10,11,12]    ]       #This is a 4*3 Matrix
np.reshape(B,(2,6))                                     #Now it is reshaped into a 2*6 matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
type(B)                                                 #Remember B is a list. 

list

In [ ]:
len(B)                                                  # length os B is 4

4

In [ ]:
type(np.reshape(B,(2,6)))                               #But....! when reshaped, it turned into a np.Array!

numpy.ndarray

In [ ]:
len(np.reshape(B,(2,6))  )                              #with length 2

2

In [ ]:
np.reshape(B,(2,6)).shape                                #and you can also use "shape" now

(2, 6)

**Numpy for mathematical operations**

In [ ]:
A = np.array( [1,2,3] )
B=  np.array( [4,5,6] )
A+B

array([5, 7, 9])

In [ ]:
A = np.array( [1,2,3] )
B=  np.array( [4,5,6] )
A * B

array([ 4, 10, 18])

In [ ]:
A = np.array( [1,2,3] )
np.sum(A)

6

In [ ]:
A = np.array( [1,2,3] )
A.sum()

6

In [ ]:
A = np.array( [1,2,3] )
B=  np.array( [4,5,6] )
np.dot(A,B)

32

In [ ]:
A = np.array( [1,2,3] )
B=  np.array( [4,5,6] )
A .dot(B)

32

In [ ]:
A = np.array( [1,2,3] )
np.linalg.norm(A)           #Gives the norm (i.e. magnitude) of the array

3.7416573867739413

In [ ]:
A = np.array( [1,2,3] )
( np.sum(A**2)) **0.5        #To check magnitude of the array

3.7416573867739413

In [ ]:
A = np.array([0, 1 ,10])

print( np.sqrt(A) )
print( np.tanh(A) )
print( np.cos(A) )
print( np.arccos(A) )
print( np.exp(A) )
print( np.log(A) )
print( np.log10(A) )


[0.         1.         3.16227766]
[0.         0.76159416 1.        ]
[ 1.          0.54030231 -0.83907153]
[1.57079633 0.                nan]
[1.00000000e+00 2.71828183e+00 2.20264658e+04]
[      -inf 0.         2.30258509]
[-inf   0.   1.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in arccos
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log10
  if __name__ == '__main__':


**Numpy Matrix**

In [ ]:
L = [ [1,2,3] , [4,5,6] ]               #Creating a matrix with Python Lists
L

[[1, 2, 3], [4, 5, 6]]

In [ ]:
#  L[0,1]                              #This would not work!!
L[0][1]                                #Row 0, Column 1

2

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )    #Creating a matrix with Numpy arrays
M

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )

print("Length of M: ", len(M))
print("Shape  of M:", M.shape)

Length of M:  2
Shape  of M: (2, 3)


In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
M[0,1]                                 #This one does work!!

2

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
M[:,2]

array([3, 6])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
M[0,:]

array([1, 2, 3])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
np.sqrt(M)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
np.exp(M)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

**Linear ALgebra in Numpy**

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )
M.T    #M Tanspose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
M = np.array( [ [1,2] , [4,5] ] )
np.linalg.det(M)

-2.9999999999999996

In [ ]:
M = np.array( [ [1,2] , [4,5] ] )
np.linalg.inv(M)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [ ]:
M = np.array( [ [1,2] , [4,5] ] )
M_inv = np.linalg.inv(M)
np.matmul(M, M_inv)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] ) 
np.diag(M )                                #matrix does not need to be Square to have a DIAGONAL !!

array([1, 5])

In [ ]:
np.diag( [1,2,3])                         # np.diag can get a list (or an array) and return a matrix with its DIAGONAL being that List

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
M = np.array( [ [1,2,3] , [4,5,6] ] )  
N = np.array( [ [0,1,4] , [1,0,3] ] )    

M*N                                        # all elements are multiplied one-by-one  when using *

array([[ 0,  2, 12],
       [ 4,  0, 18]])

In [ ]:
M = np.array( [ [1,2] , [4,5] ] )  
N = np.array( [ [0,1,4] , [1,0,3] ] ) 

np.dot(M,N)                               #Matrix multiplication   (2x2)(2,3)--->(2,3)
np.matmul(M,N)                            #Matrix multiplication   (2x2)(2,3)--->(2,3)

array([[ 2,  1, 10],
       [ 5,  4, 31]])

In [ ]:
#Solving a system of linear equations: A.x=b
A = np.array ( [  [1 ,3 ,10], [0.5, 1, 5] , [1 , 10, 20] ] )
b = np.array ( [44 ,18, 110 ] ) 

solution = np.linalg.solve(A,b)    
solution

array([10.,  8.,  1.])

**Generating special matrices**

In [ ]:
np.eye ( 3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(  (3,4)  )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(  (3,4)  )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**Generating Random Numbers**

In [ ]:
np.random.seed(123)
np.random.random(2)            #Returns 2 random number from UNIFORM distribution

array([0.69646919, 0.28613933])

In [ ]:
np.random.seed(123)
np.random.random(  (2,3)  )     #Returns a random 2x3 matrix from UNIFORM distribution

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [ ]:
np.random.seed(123)
np.random.randn(2)             #Returns 2 random number from STANDARD NORMAL distribution

array([-1.0856306 ,  0.99734545])

In [ ]:
np.random.seed(123)
np.random.randn(2,3)           #Returns a random 2x3 matrix from STANDARD NORMAL distribution

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

In [ ]:
np.random.seed(123)
R = np.random.normal(6, 2, 1000)             #Returns 1000 random number from NORMAL distribution with mean=6 and std=2

print ( 'Mean is:', R.mean()  )
print ( 'Variance is:', R.var()  )
print ( 'St. Dev.  is:', R.std()  )

Mean is: 5.920871727838416
Variance is: 4.006302780991224
St. Dev.  is: 2.001575075032467


In [ ]:
np.random.seed(123)
R = np.random.randn(10,3)                            #Returns a random 10x3 matrix from STANDARD NORMAL distribution
print ( 'Mean of each column is:', R.mean(axis=0)  )
print('\n')
print ( 'Mean of each row is:', '\n', R.mean(axis=1)  )

Mean of each column is: [-0.0800731  -0.29081877 -0.18122091]


Mean of each row is: 
 [ 0.60693432  0.43845917 -0.04947817 -1.52288921 -0.2850658  -0.36698984
 -0.17847011 -0.71833945 -0.45645671  0.69191986]


In [ ]:
R = np.random.normal(6,2, (10,3))                     #Returns a random 10x3 matrix from NORMAL distribution with mean=6 and std=2
print ( 'Mean of each column is:', R.mean(axis=0)  )
print('\n')
print ( 'Mean of each row is:', '\n', R.mean(axis=1)  )

Mean of each column is: [6.05942682 6.46654977 5.02070482]


Mean of each row is: 
 [4.99281983 5.47803527 5.57267539 4.95484134 5.23434533 7.13628339
 4.24868071 6.95151088 6.34332544 7.57642046]


In [ ]:
np.random.randint(5, 12, 10)                        #Returns 10 random integers in [5,12)

array([ 5,  9,  5, 11, 11,  5,  5,  6, 11,  7])